/******************************************************************************

Rename this file to Secrets.h after modifying!

******************************************************************************/

#ifndef SECRETS_H
#define SECRETS_H

// HERBS Data Types
#include <include/Herbs.h>

#define TO_STRING(S)    _TO_STRING(S)
#define _TO_STRING(val) #val

#define WIFI_SSID       ""
#define WIFI_PASSPHRASE ""
#define HTTP_HOST       ""
#define HTTP_PORT       1234

static const char* CLIENT_CERT = "-----BEGIN CERTIFICATE-----\n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL \n"
"LOL LOL LOL ==\n"
"-----END CERTIFICATE-----";

#define APIARY_ID       "01234567-8901-2345-6789-012345678901"
#define GATEWAY_ID      1 // Must not be 0 and less than 256

const std::unordered_map<uint64_t, MonitorEncryption> knownMonitors = {
  {0x0000000000000000, {"0000000000000000", "00000000"}}
};

#endif